[app]
title = MusicEditor
package.name = musiceditor
package.domain = com.musiceditor.app
source.include_exts = py,png,jpg,kv,atlas,ttf,otf
source.include_patterns = assets/*
version = 0.1
version.code = 1
source.dir = .
requirements = python3,kivy,mutagen
android.permissions = CAMERA, WRITE_EXTERNAL_STORAGE
output_dir = bin
icon.filename = assets/image/icon.png
android.statusbar_color = #000000
android.api = 31
android.ndk = 21b
android.sdk = 31
debug = 1
p4a.branch = master
